### ISSUE TITLE
Get exception if Person is in a class library

### ISSUE THREAD

**Issue by daramire** [Blazored/FluentValidation#1]
I am unable to make it to work if I move Person to a class library
I added "@using SharedModels.Models" in root _Imports.razor

![image](https://user-images.githubusercontent.com/7254799/59729099-7c080100-9202-11e9-9efb-eb903ea37474.png)

but get a null exception when it tries to validate
![image](https://user-images.githubusercontent.com/7254799/59729113-904bfe00-9202-11e9-9d55-5d2a24233769.png)

**Comment by chrissainty** [comment]
Thanks for reporting this @daramire. I've found the issue and should have a new version out with the fix shortly.
