### ISSUE TITLE
[Question] How would one going about getting the error message for a field?

### ISSUE THREAD

**Issue by wa1gon** [Blazored/FluentValidation#103]
Greetings,

I am loving this framework.  However, the one thing I would like to do is to put the error message into a tooltip.  The tooltip component in question is the tooltip from your blog.

Any suggestions on how to do this?

thanks

**Comment by chrissainty** [comment]
You would need to call the `GetValidationMessages method on the `EditContext`

https://github.com/dotnet/aspnetcore/blob/26d3ba3a33a7fb934f34e9e8d7c451cad56b5cee/src/Components/Forms/src/EditContext.cs#L135

There is nothing specific about this library for that.
