### ISSUE TITLE
[Question] Guidance on incorporating server-side validation results?

### ISSUE THREAD

**Issue by adam-becker** [Blazored/FluentValidation#110]
Hello,

I am trying to make fluent validation work on the client (for simple checks) and on the server (for detailed checks). I know how some of this can be achieved, but I would like some guidance on how you think this should be done. The server can (and will) send back the errors in the response body (HTTP/TCP stack), those are deserialized by the client and then .. what happens from there? The goal is to just show the server validation errors in a summary because the properties aren't likely to match up. Here's some sample code for the approach I'm taking.

```csharp
// Shared
public record Example(string Name, DateTime Start, DateTime End, string LicenseNumber) { }

public class ExampleValidator : AbstractValidator<Example> {
    // Validate name is required, start/end date form a proper range, etc.
    // Only the _shape_ of the license number is validated.
}

// Server-only
// The context is loaded separately to build a complete model that can then be validated without I/O in the middle.
// The separate type also simplifies DI configuration.
public record ExampleWithContext(Example Example, Context Context) { }

public class ServerExampleValidator : AbstractValidator<ExampleWithContext> {
    // Server re-runs the shared validation rules.
    // The actual license itself is validated by a 3rd party service.
}
```

The requirements for this aren't very flexible, this is basically the design I have to implement. For example, I can't do this all client-side.

**Comment by chrissainty** [comment]
This sounds out of scope of what this library does. I'd suggest asking on the Fluent Validation repo.
