### ISSUE TITLE
How do we get at an entity's Id in the validation?

### ISSUE THREAD

**Issue by MrYossu** [Blazored/FluentValidation#115]
Just looking at the sample code, specifically at the email validation. 

How can we get at the `Id` of the `Person` (I know the one in the sample doesn't have an `Id` property, but imagine this is a database model, it wold have). We would need that in the `IsUniqueAsync` method. We could code the method as follows (assuming an injected `AppDbContext`)...

```c#
    private async Task<bool> IsUniqueAsync(string email) =>
      await AppDbContext.People.AllAsync(p => p.Email != email);
```

This would work fine for a new `Person`, as there wouldn't be an entity with the email, but if we were updating an existing `Person`, then the `IsUniqueAsync` would return `false` and the validation would fail.

How can we get at the `Id` of the `Person` in the validation?

Thanks

**Comment by MrYossu** [comment]
Just discovered the `Custom` method, but it doesn't seem to work here. I tried the following rule...

```c#
    RuleFor(p => p.Email).Cascade(CascadeMode.Stop)
      .NotEmpty().WithMessage("required")
      .EmailAddress().WithMessage("invalid")
      .Custom(async (email, ctx) => {
        Investor me = ctx.InstanceToValidate;
        if (await _appDbContext.Investors.AnyAsync(inv => inv.ID != me.ID && inv.Email == email)) {
          ctx.AddFailure("exists");
        }
      });
```

When I run this, and enter an email that exists for another entity, the failure is added to the context (I see that when setting a breakpoint), but the error isn't shown in the UI. If I leave the email blank, the error is shown in the UI.

Is this the correct way to signal a validation error? If not, what is?

Thanks

**Comment by Sharaf-Mansour** [comment]
@MrYossu Try downgrading to 2.0.1.
2.0.3 has few issues when showing errors on UI.

**Comment by MrYossu** [comment]
@Sharaf-Mansour Nope, still doesn't show anything in the UI even with v2.0.1.

Any other ideas? Thanks

**Comment by MrYossu** [comment]
@Sharaf-Mansour Duh, I just realised that part of the problem is that I'm using standard HTML `input` elements, not the Blazor ones. Looks like I need to rework some code!

Thanks

**Comment by Sharaf-Mansour** [comment]
Try the blazor component and set Validators For. And EditForm. And if it does not work. I will be happy to take a 2nd look into your code :D and get some idea to make it work.

**Comment by chrissainty** [comment]
I'm closing this as it doesn't seem to be to do with this library more a general how do I do x with Fluent Validation.
