### ISSUE TITLE
[Bug] Delete the content of textbox without checking validation.

### ISSUE THREAD

**Issue by HTTPThanhLuan** [Blazored/FluentValidation#123]
https://blazored.github.io/FluentValidation/

There is no validation. If I delete the content of textbox of nested type (for example: Address: Line 1)

**Comment by Sharaf-Mansour** [comment]
I Talked about this in #104 and Downgrading to version 2.0.1 Fixes the problem

**Comment by chrissainty** [comment]
I'm closing this as a duplicate of #104
