### ISSUE TITLE
Update and test with FluentValidation 11.0.0

### ISSUE THREAD

**Issue by KuraiAndras** [Blazored/FluentValidation#126]
**Is your feature request related to a problem? Please describe.**
Updating `FluentValidation` to `11.0.0` produces errors as `Blazored.FluentValidation` hasd a constraint on the version `>= 10.2.1 && < 11.0.0`

**Describe the solution you'd like**
Update and test `Blazored.FluentValidation` to safely work with 11.0.0

**Describe alternatives you've considered**
None

**Additional context**
[Migration Guide](https://docs.fluentvalidation.net/en/latest/upgrading-to-11.html)

**Comment by chrissainty** [comment]
This is now available to test https://www.nuget.org/packages/Blazored.FluentValidation/2.1.0-preview.1
