### ISSUE TITLE
[Bug] Tick icon in a valid text input only displays if the input has a "placeholder" attribute.

### ISSUE THREAD

**Issue by boyfonz** [Blazored/FluentValidation#128]
**Describe the bug**
Tick icon in a valid text input only displays if the input has a "placeholder" attribute. 

I have two identical forms.

The first does not have any "placeholder" attributes on the text inputs. When a valid value is typed into the field, the outline of the input turns green, but no tick icon appears on the right. Inspecting the element in Chrome shows the background image of the tick is crossed out.

The second form is identical but it has a "placeholder" attribute, with a value. Typing a valid value into this box gives the green outline and a tick icon on the right.

An invalid value in both cases gives a warning icon and a red outline.

**Screenshots**
![image](https://user-images.githubusercontent.com/295673/166936324-1ecc6b4e-2b08-4f2b-8813-209e0d5e72e5.png)
In this example, the first input field has a placeholder attribute, while the second and third do not.

**Hosting Model:**
 - Blazor WebAssembly
 - using FluentValidation
 - have encountered the issue with and without BlazorStrap
 - using Bootstrap 5
 - tested in Chrome

**Comment by chrissainty** [comment]
Hi @boyfonz,

Sorry to hear you're having issues. Unfortunately, I don't think this is anything to do with Blazored FluentValidation. This library doesn't control anything related to styling or even applying the various styling classes that Blazor's form components use.

**Comment by boyfonz** [comment]
Thanks for clearing that up! 👍
