### ISSUE TITLE
Validation message to clear automatically on valid data

### ISSUE THREAD

**Issue by hgirma** [Blazored/FluentValidation#129]
Not sure if this is possible but would be nice if the validation message auto clears when the input has valid data, currently the user will have to click on submit once more to clear the validation error message.

**Comment by chrissainty** [comment]
Hi @hgirma, that isn't controlled by this library, it's controlled by you and how you've chosen to bind your model values to the inputs. 

If you just use bind, then values only update when focus is lost. This is when validation would be return as well. If you use bind, but also specify that it should use the oninput event, then everything will update after each keystroke:

@bind:event="oninput"

**Comment by hgirma** [comment]
Hello, that didn't work,  

consider the following simple form.

```
<EditForm Model="@myModel"  OnValidSubmit="SubmitValidForm">
 <FluentValidationValidator />
 <input class="form-control" id="inputUserName" @bind="@myModel.UserName"  @bind:event="oninput"/>
 <label for="inputUserName">UserName</label>
 <ValidationMessage For="() => myModel.UserName" />
 <input type="submit" class="btn btn-primary" />
</EditForm>
```
the only way to clear up the error message is to re-submit the form once more, I was hoping that it would clear automatically like the unobtrusive jquery validations. It may be a blazor issue vs the library, not sure...

**Comment by chrissainty** [comment]
One thing I can spot from your code is that you're not using Blazor's form components, InputText, InputNumber, etc... You're using standard HTML inputs.

**Comment by hgirma** [comment]
Yep, that was it, it worked as expected when switching to InputText. Thank you!
