### ISSUE TITLE
Support multiple validators

### ISSUE THREAD

**Issue by grishat** [Blazored/FluentValidation#135]
Thanks for project.
I have several validators for same object in different projects.  And all of them should be validated.

**Comment by Sharaf-Mansour** [comment]
You are relaying on the assembly scanner to check for the validators.
In your case you would want to register the validation manually. 
Is it really necessary to validate the same object in multiple projects?

**Comment by grishat** [comment]
In my case, I have a product with two editions: Community (CE) and Business Editions (BE). In BE I'm adding additional validations, for example max number of some objects creation. So the validators for same object are in different projects.

**Comment by Sharaf-Mansour** [comment]
Why not making the validations as a shared project / Library as itself and do something like
```csharp
RuleFor(x => x.Qty).Max(20).When(x=> x.Edition is Editions.CE);
RuleFor(x => x.Qty).Max(100).When(x=> x.Edition is Editions.BE);
```

**Comment by Sharaf-Mansour** [comment]
You have 2 Models for same validator at least put some context that tells the validator to (use which and when).
I recommend wrapping this in a parent Validator.

**Comment by chrissainty** [comment]
Thanks for the help triarging this one @Sharaf-Mansour 👍

**Comment by Sharaf-Mansour** [comment]
My duty captain 🫡
