### ISSUE TITLE
Not compatible with Latest Fluent vaildator 11.02

### ISSUE THREAD

**Issue by ltemimi** [Blazored/FluentValidation#136]
I installed the lates FluentValidation 11.02 then I nstalled  Blazored.FluentValidation 2.03 Visual studio tells me they are not compatible and need FluentValidation version less than 11.0

**Comment by chrissainty** [comment]
You need to install the latest [preview version](https://www.nuget.org/packages/Blazored.FluentValidation/2.1.0-preview.1) of the package, this supports FluentValidation 11+.
