### ISSUE TITLE
Using ASP.NET automatic validation with asynchronous rules

### ISSUE THREAD

**Issue by PeterDraex** [Blazored/FluentValidation#141]
Hi,

I'm getting the following error:
```
The validator "RegistrationModelValidator" can't be used with ASP.NET automatic validation as it contains asynchronous rules.
```

For which I found the following explanation in the [docs](https://docs.fluentvalidation.net/en/latest/async.html#asynchronous-validation):
> You should not use asynchronous rules when [using automatic validation with ASP.NET](https://docs.fluentvalidation.net/en/latest/aspnet.html) as ASP.NET’s validation pipeline is not asynchronous. If you use asynchronous rules with ASP.NET’s automatic validation, they will always be run synchronously (10.x and older) or throw an exception (11.x and newer).

What was the reason for this change? Is there an option to revert to the 10.x and older behavior? If not, you can consider this a feature request :). It would be useful for me, as I'm trying to use the same validation rules in Blazor WebAssembly as on the server side, according to [this tutorial](https://jonhilton.net/blazor-client-server-validation-with-fluentvalidation/).

**Comment by chrissainty** [comment]
Hi @PeterDraex, I think you have the wrong repo. This isn't the [FluentValidation repo](https://github.com/FluentValidation/FluentValidation), this is a library to allow it to be used in Blazor.
