### ISSUE TITLE
[Bug] FluentValidation v11+ support

### ISSUE THREAD

**Issue by jimitndiaye** [Blazored/FluentValidation#144]
**Describe the bug**
the current package explicitly excludes versions of Fluent Validation 11.0 and above

**To Reproduce**
1. Reference this package
2. Attempt to add a reference to the latest versions of FluentValidation (11.0 and above)
3. See error

**Expected behavior**
Able to work with newer versions of Fluent Validation

**Comment by chrissainty** [comment]
This by design as there could be breaking changes with a new major version (this has happened previously). 

Version 11 is supported in the latest preview package. You will need to install this if you want v11 support in the short term.
