### ISSUE TITLE
Create please new version with updated package FluentValidation (11.x.x)

### ISSUE THREAD

**Issue by tatti9018** [Blazored/FluentValidation#145]
Create please new version with updated package FluentValidation (11.x.x). I really wait for it.

**Comment by chrissainty** [comment]
Please search existing issues before raising a new one. I'm getting tired of repeating myself.

**Comment by scottkuhl** [comment]
> Please search existing issues before raising a new one. I'm getting tired of repeating myself.

I think a lot of people aren't searching the closed issues.  It might help to leave #126 open until it leaves beta and maybe even pin the issue until then.
