### ISSUE TITLE
Make FluentValidation responsiveness based on mouse/key-up rather then input change for better UX?

### ISSUE THREAD

**Issue by NatanBagrov** [Blazored/FluentValidation#15]
Hi,
First of all - great work!
The current solution is great, however I find it annoying in cases where `text` inputs are constrained to have min/max length (this is just one example).

Use case:
Suppose we have a field named "Name" and the constraints is that the length is at least 2 letters.
Say we have pre-validated the form so the user sees that "Minimum length of 2 is required".
When a user types 2 letters, the validation message does not disappear until he clicks somewhere - usually the next click is on the "Submit" button, but if this button is being activated by the form being valid or not - we have a problem - since it is not valid.

I really hope I made myself clear...
Maybe this is the intended behavior though, I don't know...

Cheers!

**Comment by chrissainty** [comment]
Hi @NatanBagrov,

I'm glad you like the library :)

So your issue isn't anything to do with this library it's the event you're binding to on your input control. By default when you using `@bind-Value` on a `InputText` component, Blazor will update the bound value when the control loses foucs. If you want the bound value to be updated on each keystroke you can instead bind to the `input` event. Like this:

 `<InputText @bind-Value="MyVariable" @bind-Value:event="oninput" />`

**Comment by NatanBagrov** [comment]
> Hi @NatanBagrov,
> 
> I'm glad you like the library :)
> 
> So your issue isn't anything to do with this library it's the event you're binding to on your input control. By default when you using `@bind-Value` on a `InputText` component, Blazor will update the bound value when the control loses focus. If you want the bound value to be updated on each keystroke you can instead bind to the `oninput` event. Like this:
> 
> `<InputText @bind-Value="MyVariable" @bind-Value:event="oninput" />`

Hmm... that does not seem to work :( it does with `<input type="text".../>` but then the validation messages do not show correctly.

**Comment by chrissainty** [comment]
My apologies, @NatanBagrov. I was a bit jet lagged yesterday and my brain wasn't working properly!

You're correct it won't work with the default `InputText` component as it's hard-coded to use the `OnChange` event. If you want this behavior you will need to write you own component I'm afraid. We've done this at work and it's pretty simple. You can use the [out of the box components](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Web/src/Forms/InputText.cs) as a guide.
