### ISSUE TITLE
[Question] Release new package with FluentValidation v11 support

### ISSUE THREAD

**Issue by hakenr** [Blazored/FluentValidation#153]
Current v2.0.3 is restricted to FluentValidation <11.x
There is a v2.1.0-preview.2 published but still as a prerelease.
We would like to upgrade to FluentValudation v11 in our production projects without having to rely on prerelease package.

Will the v2.1.0 be release any soon?
Is there anything I can help with to make it done?

**Comment by hanslai** [comment]
This issue happened over and over again,I would suggest that this project does not set the upper version limit for FluentValidation.  Most of the github package do not set the upper version limit unless it really have to anyway.

**Comment by hanslai** [comment]
I would also like to note that even "2.1.0-preview.2" is limited to FluentValidation(>= 10.2.1 && 11.0.0), Yet, FluentValidation 11.1.0 was released already.    This is create troubles for projects that both frontend and backend refer to the same model project require FluentValidation.

As suggested in the earlier comment, I believe it will be easier just to take out the upper version limit for FluentValidation.

**Comment by chrissainty** [comment]
@hanslai im not sure if I've misunderstood but the preview 2 package isn't restricted. It requires a version of 11.0.0 or higher as per the [docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-version)

**Comment by hanslai** [comment]
@chrissainty Thanks for your reply.   I just double checked, indeed preview 2 isn't restricted, my bad.
I checked on VS nuget package management before I posted the comment, but I believe I was look at 2.0.3, but thought I was looking at preview 2.  Sorry for the mistake.

**Comment by mhsimkin** [comment]
@chrissainty any estimate when 2.1 will be released and no longer a preview? Thanks

**Comment by hakenr** [comment]
Resolved with v2.1.0.
