### ISSUE TITLE
FluentValidation doesn't work when I change Validators folder

### ISSUE THREAD

**Issue by Camilo193** [Blazored/FluentValidation#175]
I am using FluentValidation to do the validations both in the Backend and in the forms in the Frontend.
Due to architecture decisions I had to move the validations to another namespace.
I changed the references of the validations in the program class in the backend and it continues to work without problems in the backend, but now it doesn't work in blazor, it only works if I put the validations in the old project.
I already cleaned the project, I did a rebuild, I cleaned browser data, but for some unknown reason the validations in the Frontend still don't work.

![namespace](https://user-images.githubusercontent.com/14241227/212353205-d6b4cf09-a1be-4da3-b5a3-248481326efb.jpg)

In the program class (Backend), I changed the reference of the validations and it works fine in the backend, but now it doesn't work on the Frontend (If I change the validations to the old folder it would work). But I can't return the validations to the old folder due to architecture decisions

![reference](https://user-images.githubusercontent.com/14241227/212354922-bddc79ee-9c0e-4d66-85e6-df0132407575.jpg)

These are the validations in the frontend that now do not work. It seems as if the old reference was saved in memory and now it does not take the new namespace where the validations are.

![Forms](https://user-images.githubusercontent.com/14241227/212355068-38f2ba15-c5a4-4622-848f-6af9ab6c23a2.jpg)

I did a curious experiment.
I Pass a validation file to the old folder with a random namespace which is not referenced by anything and for some strange reason, it works. This doesn't make sense to me

![validations old folder](https://user-images.githubusercontent.com/14241227/212355320-ab0dd163-2c8f-4bf4-bd72-36a5b164c653.jpg)

There's my Server program class

![Back program class](https://user-images.githubusercontent.com/14241227/212355903-e7d4e226-979c-47cc-a1ae-a3c8e5927953.jpg)

There's my Client program class

![Client program class](https://user-images.githubusercontent.com/14241227/212355945-8d9bfd5a-567a-405d-84da-8edaf3f0c693.jpg)

I'm using Blazor Web Assembly 7 and .Net 7

¡Thank you!

**Comment by chrissainty** [comment]
It doesn't look like you've registered you validators with your Blazor project. By default the component looks for the validator via DI. That would explain why things aren't working. Has that code been deleted from the Program.cs by mistake?

**Comment by Camilo193** [comment]
> Has that code been deleted from the Program.cs by mistake?

Previously I didn't have them registered in the client program either, but it worked, it only stopped working when I changed the validator classes folder.

**Comment by Camilo193** [comment]
> It doesn't look like you've registered you validators with your Blazor project. By default the component looks for the validator via DI. That would explain why things aren't working. Has that code been deleted from the Program.cs by mistake?

I uploaded this video to try to explain the probem that I have.

https://www.youtube.com/watch?v=vA8FxkYEQr8

(Sorry for my english 😄)

**Comment by Camilo193** [comment]
![image](https://user-images.githubusercontent.com/14241227/212390489-3dcd10da-f251-4251-86be-d7ac77896e88.png)

It had always worked for me without making the references in the client program class, but now I add the references and now it's working.

Thank you chrissainty.
