### ISSUE TITLE
[Bug] Getting validator class from assembly doesn't gracefully handle ReflectionTypeLoadExceptions.

### ISSUE THREAD

**Issue by pwinstead** [Blazored/FluentValidation#23]
**Describe the bug**
GetValidatorForModel doesn't gracefully handle scenarios where the assembly reference throws any ReflectionTypeLoadExceptions.   Resulting in a hard error.

**To Reproduce**
In my example, I have reference to Microsfot.JSInterop.WebAssembly.dll from a project dependency. I have a data model tied to an form which doesn't have a backing IValidator<> for that model type. This only matters because if I did have the a backing IValidator<> the order in which assemblies evaluate means a successful Validator is found prior to hitting the assembly that throws the error. 

When I run my project and start interacting with the form it will hit a hard error when it Microsfot.JSInterop.WebAssembly.dll is attempted to be loaded as a part of GetValidatorForModel.  Here is a detailed look at the exception thrown.

![image](https://user-images.githubusercontent.com/37338963/81133951-2ecb7580-8f21-11ea-8956-ca9593e72daf.png)

**Expected behavior**
I would instead expect the error to be caught gracefully and then continue evaluating other assemblies. In my scenario it would eventually return null since I don't have a backing IValidator<>.

**Hosting Model**
Currently running Blazor Server, but I don't actually hit this issues when just running the site. I hit this issue when running Selenium Tests in a different project that hosts and interact with Blazor site. This is why I mention above that the Microsfot.JSInterop.WebAssembly.dll reference comes from a project dependency (my blazor project). I'm not super familiar with assembly referencing in code so wasn't sure if this was worth mentioning or not.

**Comment by chrissainty** [comment]
This sounds like that same problem reported in issue #20. Would you agree?

**Comment by pwinstead** [comment]
Yes it does sound the same as the root issue mentioned in #20 but then the conversation got off track and the last few comments made me think that a separate bug was necessary to open.

**Comment by pwinstead** [comment]
Additional thought, it might be nice to have the option to avoid the 'assembly traversing' logic all together and instead require DI for all validators.

**Comment by chrissainty** [comment]
> Additional thought, it might be nice to have the option to avoid the 'assembly traversing' logic all together and instead require DI for all validators.

We do try and get the validator from DI before we scan the assemblies, currently. Are you suggesting something more aggressive, like having a parameter which turns off the assembly scanning option altogether?

**Comment by pwinstead** [comment]
> > Additional thought, it might be nice to have the option to avoid the 'assembly traversing' logic all together and instead require DI for all validators.
> 
> We do try and get the validator from DI before we scan the assemblies, currently. Are you suggesting something more aggressive, like having a parameter which turns off the assembly scanning option altogether?

Yes, I like the convention of relying on DI for my validators and although the assembly scan is definitely a feature I could see people use. I would personally lean towards DI only approach and avoid any performance costs the assembly scan my have while it's looking for a validator which in our case doesn't exists. It would also prevent the issue I'm currently hitting.

**Comment by chrissainty** [comment]
I disagree a DI only approach is the best way to go, flexibility is important. But I think adding in a parameter which turns it off so that if a developer chooses, they can enforce DI only behaviour.

**Comment by pwinstead** [comment]
Thanks for the quick turn around on this @chrissainty!
