### ISSUE TITLE
Addding reference via nuget package

### ISSUE THREAD

**Issue by bessobesso** [Blazored/FluentValidation#28]
When I add Blazored.FluentValidation via Nuget then it throws exception
 Unhandled exception rendering component: Method not found: System.Threading.Tasks.Task`1<FluentValidation.Results.ValidationResult> FluentValidation.IValidator.ValidateAsync(object,System.Threading.CancellationToken)

However when I add Blazored.FluentValidation from your sample then it works fine.

**Comment by chrissainty** [comment]
Hi @bessobesso, I'm not sure what the issues based on the information provided. I've just created a new app and installed the package and everything appears to be working as expected. 

Can you please put together a working minimal repro of the issue so it can be investigated.

**Comment by bessobesso** [comment]
Hi, here is the repo which is not working, on Index page there is 1 single input and it throws exception when you click on submit.
https://github.com/bessobesso/BlazorFluentValidationTest

**Comment by dj-doMains** [comment]
I'm having the same issue. If I use the nuget package I get the same exception.

However if I bring in `EditContextFluentValidationExtensions.cs` and `FluentValidationsValidator.cs` directly into my project everything works as expected.

Maybe there's a dependency incompatibility somewhere?

**Comment by lthoa** [comment]
I have tried and found that Blazored.FluentValidation version 1.3.0 via Nuget is not compatible with version FluentValidation 9.0.0, it is only compatible with version FluentValidation 8.6.2. 

Version 1.3.0 on Nuget has not updated to the latest source code like on Github.

**Comment by chrissainty** [comment]
Hey all thanks for your comments, as @lthoa points out this is due to a breaking change in FluentValidation v9. We've alreay merged a PR to fix it and I'm looking to get that out at some point today.

**Comment by chrissainty** [comment]
This should now be resolved with version 1.3.1
