### ISSUE TITLE
[Bug] use of {CollectionIndex} in RulesForEach

### ISSUE THREAD

**Issue by Flearz** [Blazored/FluentValidation#29]
Hello

**Describe the bug**
Using "CollectionIndex" not working, it is writing {CollectionIndex} instead of the actual index when updating to version 9.0.0 of FluentValidation.  I don't kwow if it's your side problem or original project problem.

**To Reproduce**

public class PersonValidator : AbstractValidator<Person> {
  public PersonValidator() {
    RuleForEach(x => x.AddressLines).NotNull().WithMessage("Address {CollectionIndex} is required.");
  }
}

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**
Working with version 9.0.0 preview 4

Doc: https://docs.fluentvalidation.net/en/latest/collections.html

Thanks in advance

**Comment by chrissainty** [comment]
Hey @Flearz, could you provide repro of the issue please? I've been trying to replicate it but I can't seem to get a working app.

**Comment by chrissainty** [comment]
As there has been no further feedback on this I'm going to close the issue. If you can provide more information then please reopen it and we can taker another look.
