### ISSUE TITLE
[Bug] Dto Validator Rule not working as expected

### ISSUE THREAD

**Issue by pauladiazl** [Blazored/FluentValidation#32]
**Describe the bug**
I am using the code below as a rule for a Dto Validator and it is not respecting the NotNull() condition and it is displaying the message even after the DVToolAnswer question has been answered (after it is no longer null).

RuleFor(x => x.DvToolAnswer).NotNull().WithMessage("At least 1 DV Tool option must be selected").When(x => x.WellViewName == "INTCSG1" && x.ActivityOptionId == ActivityOptionId.AvgOfLastPad);

**To Reproduce**
1. Go to modal in app (modal has a question with two radial buttons)
2. Try to submit the form/modal without selecting an option to display the message (validator works as expected)
3. After confirming that validator is working correctly, proceed to choose one of the radial buttons expecting the message goes away. 
4. See error = Message from validator is still showing even though an option has been selected. It does let me submit the form.

**Expected behavior**
The message from the DtoValidator should no longer appear once an option has been selected

**Screenshots**
![image](https://user-images.githubusercontent.com/68753067/88436132-43553680-cdc9-11ea-8d29-37967f000d6b.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by chrissainty** [comment]
Hi @pauladiazl, is there something which makes you think this is a problem with this library and not something else?

Are you seeing errors anywhere?

**Comment by bancroftway** [comment]
The main issue is that validation error does not go away even when radio button is selected. In the code below, there is a radio button, and if the first radio button's selected value is 1, then a second radio button is shown. The validation is working as expected, but for the second radio button, the red error message does not go away, even when value has been selected.  Here is the relevant code:

```
<EditForm Model="@CurrentSection" OnValidSubmit="@ConfirmActivityOptionsModal">
                <FluentValidationValidator />    
                <!--Radio button #1-->        
                <div class="radio" style="margin-left: 70px">
                    <label>
                        <input name="optradio" type="radio" id="dp-slectinput"
                               value="1"
                               checked="@(CurrentSection?.ActivityOptionId == 1
                               @onchange="@(() => { CurrentSection.ActivityOptionId = 1;})" />
                        Option 1
                    </label>
                </div>
                <div class="radio" style="margin-left: 70px">
                    <label>
                        <input name="optradio" type="radio"
                               value="2"
                               checked="@(CurrentSection?.ActivityOptionId == 2)"
                               @onchange="@(() => { CurrentSection.ActivityOptionId = 2; })" />
                        Option 2
                    </label>
                    <ValidationMessage For="@(() => CurrentSection.ActivityOptionId)" />
                </div>
                @if (CurrentSection.Name == "SomeName" && CurrentSection.ActivityOptionId == 1)
                {
                     <!--Radio button #2. This is shown only if above radio button's selected option is 1-->        
                    <span class="font-weight-bold" style="text-align:center;margin-left:70px"> Question #2</span>
                    <div class="radio" style="margin-left: 70px">
                        <label>
                            <input name="optradio1" type="radio"
                                   checked="@(CurrentSection.Question2 == true)"
                                   @onchange="@(() => { CurrentSection.Question2 = true; })" />
                            Yes
                        </label>
                    </div>
                    <div class="radio" style="margin-left: 70px">
                        <label>
                            <input name="optradio1" type="radio"
                                   checked="@(CurrentSection.Question2 == false)"
                                   @onchange="@(() => { CurrentSection.Question2 = false; })" />
                            No
                        </label>
                        <ValidationMessage For="@(() => CurrentSection.Question2)" />
                    </div>
                }
                <button class="btn btn-secondary" type="button" @onclick="@CancelActivityOptionsModal">Cancel</button>
                <button class="btn btn-primary" type="submit">Confirm</button>
            </EditForm>
```

**Comment by pauladiazl** [comment]
> Hi @pauladiazl, is there something which makes you think this is a problem with this library and not something else?
> 
> Are you seeing errors anywhere?

Hi @chrissainty is the information below provided by my colleague enough to understand the issue? The bug is still happening for all of our validators. Thanks!

**Comment by chrissainty** [comment]
Hi @pauladiazl, apologies for the delay I've been changing jobs.

Looking at the code sample provided by @bancroftway, this isn't a bug, it's a mistake in the way you've implemented your radio buttons. All form components in Blazor inherit from `InputBase` this base class performs some key actions for you, mainly, handling the integration with the underlying validation system. As you've just used native HTML elements you are not hooking into the validation system correctly and hence getting the odd behaviour you've experienced. 

I would suggest reading the section in the [official docs](https://docs.microsoft.com/en-gb/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#radio-buttons) which explains how to implement radio buttons correctly by inheriting from `InputBase`. Once you've updated your code things should start working as expected.

As there isn't a problem with the library I'm going to go ahead and close this.
