### ISSUE TITLE
[Question] What is the best way to trigger a validation when field is exited and/or changed?

### ISSUE THREAD

**Issue by wa1gon** [Blazored/FluentValidation#41]
I would like to show the user error as soon as they exit the field.  Somewhere I think I say that being done with edit contact, but that may have been with data annotations. 

Is there a recommended way to do this?

thanks
Darryl

**Comment by chrissainty** [comment]
Hi @wa1gon, this is the default behaviour. If you look at our [example site](https://blazored.github.io/FluentValidation/), you can see it in action. Enter a name in the first input and tab out and the input goes green. If you go back and remove the text and tab out it will go red.

**Comment by NPadrutt** [comment]
I actually would have the same question. I think currently the automatic trigger only works when you work with the default InputText Field. I use BlazorFluentUI and with this code the model gets updated on input, but the validation isn't executed:

        <BFUTextField Label=@Localizer["CustomerNameLabel"]
                      @bind-Value="@SelectedCustomerDto.CustomerName"
                      @bind-Value:event="oninput" />

**Comment by chrissainty** [comment]
@NPadrutt Unfortunately this sounds like it is something to do with how those frameworks have implemented their controls. I would suggest opening an issue there. This library integrates with the standard forms and validation components, or components which conform to the standard system.
