### ISSUE TITLE
[Question]Support for validator with constructor argument

### ISSUE THREAD

**Issue by simirajsp** [Blazored/FluentValidation#42]
**Please be sure to check the readme file before raising an issue.**
Fluent validation supports validators with a constructor parameter using an overload of the SetValidator method. See CollectionValidatorWithParentTests for sample. 

			var validator = new TestValidator {
				v => v.RuleFor(x => x.Surname).NotNull(),
				v => v.RuleForEach(x => x.Orders).SetValidator(y => new OrderValidator(y))
			};

I tried the same with Blazored.FluentValidation and gets an exception. This is because it is trying to get the constructor parameter from DI instead of using the already provided instance. 

Is there any way to get it working?

**Comment by chrissainty** [comment]
You need to pass the validator into the component using the `Validator` parameter. This will stop the component trying to find it in the service container.

**Comment by chrissainty** [comment]
Closed as no further communication.

**Comment by tesar-tech** [comment]
I have the same error, but not able to fix that.. How to pass validator into component??

Sample: https://blazorrepl.com/repl/QlaJQcQu19xE1lpu38

It throws the error when validation is performed on Address Line1..

Important lines:

```csharp
//AddressValidator ctor with param:
public AddressValidator(string name)
//...
//PersonValidator:
RuleForEach(p => p.Addresses).SetValidator(person => new AddressValidator(person.FirstName));
```
