### ISSUE TITLE
When clause does not seem to be working correctly

### ISSUE THREAD

**Issue by zandhaai** [Blazored/FluentValidation#44]
Given my following rule:
```
public class SomeClassValidator : AbstractValidator<SomeClass>
{
    public SomeClassValidator()
    {
        RuleFor(s => s.Id).NotEmpty().When(s => s.Active).WithMessage("Cannot be empty");
    }
}
```
Now the above is part of a list in my Blazor form (stripped HTML):

```               
@foreach (var someClassInstance in ViewModel.SomeClassList)
{
  <tr>
    <td>
      <InputText class="form-control" @bind-Value=someClassInstance.Id />
      <ValidationMessage For="() => someClassInstance.Id" />
    </td>
    <td>
      @if (someClassInstance.Active)
      {
        <button type="button" @onclick="@(() => { Delete(someClassInstance); })"><delete</button>
      }
      else
      {
        <button type="button" @onclick="@(() => { Restore(someClassInstance); })">restore</button>
      }
    </td>
  </tr>
}
```

No if I click on my delete button the validator shows a validation error which is wrong. Code delete action:

```
private void Delete(SomeClass someClassInstance)
{
    someClassInstance.Active = false;
}
```

Maybe it is something I do wrong or maybe the fluent validation is not working correctly.

**Comment by zandhaai** [comment]
Some new insights I discovered today for another (simple) form:
The when clause works, when only having 1 submit button and not an extra 'type' button like the delete button above.

**Comment by chrissainty** [comment]
Interesting, this isn't something I've been able to replicate. The logic for validating these rules is done by FluentValidation, we just call the Validate method. So it might be worth raising an issue there as this isn't something we can do anything about.
