### ISSUE TITLE
[Question] Is it possible to load a ValidationResult from JSON?

### ISSUE THREAD

**Issue by john-cullen** [Blazored/FluentValidation#47]
Hello,

Is it possible to load a ValidationResult object into the validator so that the messages get applied as appropriate? For example, some of my validations for a property may require database lookups so they aren't performed until we attempt to persist the object.

Thanks

**Comment by chrissainty** [comment]
This isn't something that is possible I'm afraid. I've heard the `MustAsync` might be working in .NET5 in which case we'll upgrade to support that.
