### ISSUE TITLE
DotNet5 Compability

### ISSUE THREAD

**Issue by jeffersantoss** [Blazored/FluentValidation#48]
After migrate the project to DotNet5 the validations is not working anymore.

**To Reproduce**
After submit the errors show up in the console tab:

**Expected behavior**
Validate the form.

**Screenshots**
![image](https://user-images.githubusercontent.com/10839497/100236926-0af76d80-2f0d-11eb-9814-779a313721f6.png)

**Hosting Model:**
 - Blazor Server

**Comment by chrissainty** [comment]
Hi @jeffersantoss, have you tried a full clean and rebuild of the solution? We use this library where I work and we've successfully upgraded a couple of projects to .NET 5 and everything is working fine.

If you're still experiencing an issue, could you try and provide a repro of it and upload it to GitHub so we can try and debug what's happening.

**Comment by Sebazzz** [comment]
This also works fine at our side.

**Comment by GioviQ** [comment]
I am using my branch https://github.com/BlazorQ/FluentValidation/tree/sync migrated to .Net 5 with mustasync fix.

**Comment by chrissainty** [comment]
@GioviQ What is the MustAsync fix?

**Comment by GioviQ** [comment]
Without that commit, I cannot have validation like the following one working


                 RuleFor(p => p.Application).MustAsync(async (application, cancellation) =>
                 {
                     bool exists = (await apiclient.GetApplications(i => i.Application == application, 1)).Any();
                     return !exists;
                 }).WithMessage("ApplicationMustBeUniqueValidationMessage");

**Comment by chrissainty** [comment]
Ah that's the change to make async validation run synchronously. 

I need to find a proper solution for async validation.

**Comment by mkopara** [comment]
I can confirm that its not working on Blazor WebAssembly. Same problem here

**Comment by jonhilt** [comment]
Hey! I seem to have run up against this too (or something very similar).

If I have this rule in my validator...

``` csharp
RuleFor(c => c.Title).NotEmpty();
RuleFor(c => c.Body).NotEmpty();

RuleFor(c => c.Slug).NotEmpty()
        .Matches("^[a-z0-9]+(?:-[a-z0-9]+)*$")
        .WithMessage(
            "Please enter a valid slug, using only alphanumeric characters and hyphens e.g. test-post")
        .MustAsync(BeUniqueSlug).WithMessage("Slug already in use, try a different one");
```

When I submit the form (which uses this validation) the validation is completely bypassed and my `HandleValidSubmit` method is invoked.

If I comment the 'slug' validator out and run it, everything works as expected.

**Comment by jonhilt** [comment]
Just found the [other issue](https://github.com/Blazored/FluentValidation/issues/38) tracking the complications that accompany async. Apologies for posting my example before I read that, don't suppose it helps really!

**Comment by chrissainty** [comment]
@jonhilt No worries. The lack of proper async support for forms validation is a real pain. I'm trying to not just resort to making async validation run synchronously like other libraries. I appreciate it get the functionality working, but it doesn't solve the problem. Not knocking other libraries here at all. 

Anyway, I'm going to close this issue as there isn't any work to do.
