### ISSUE TITLE
[Feature Request] Validator Customization

### ISSUE THREAD

**Issue by shirados90** [Blazored/FluentValidation#49]
**Is your feature request related to a problem? Please describe.**
I would like to have a possibility to specify which ruleset of injected validator will be executed against current model

**Describe the solution you'd like**
A similar to the solution in FluentValidation.AspNetCore library:
- You are able to specify rulesets by [CustomizeValidator(RuleSet = "common,create")] attribute
- Probably the best option is to define rulesets via FluentValidationValidator parameters

**Describe alternatives you've considered**
Alternatively it's still possible to have different model types amd different validators for each, which cause a lot of redundant classes created in project

**Comment by GioviQ** [comment]
Have you seen https://github.com/Blazored/FluentValidation/blob/main/samples/BlazorServer/Pages/Index.razor#L84 ?

**Comment by chrissainty** [comment]
As @GioviQ I believe this is now resolved by #45

**Comment by petgus** [comment]
Hi, sorry for digging up this old thread but....

The  example 
https://github.com/Blazored/FluentValidation/blob/main/samples/BlazorServer/Pages/Index.razor#L84 
seems to require partial validation to be triggered by clicking not the submit button but another button.

**Is there no way of selecting one or several RuleSets to be used when validating on submit?**

Consider this validator scenario where we use RuleSets to support validating address depending on country.

```
  public class UserValidator : AbstractValidator<User>
   {
        public UserValidator() {

            RuleFor(x => x.Username).NotEmpty().EmailAddress();
            RuleFor(x => x.PhoneNumber).NotEmpty().MustBeValidPhoneNumber();

            RuleSet("Password", () =>
            {
                RuleFor(x => x.Password)
                    .NotEmpty()
                    .MustBeValidPassword();

                RuleFor(x => x.PasswordConfirmation)
                    .NotEmpty()
                    .Equal(x => x.Password)
                    .WithMessage("Passwords do not match");
            });

            RuleSet("Swedish Address", () => {
                RuleFor(x => x.Address).SetValidator(new SwedishAdressValidator());
            });

            RuleSet("Norweigan Address", () => {
                RuleFor(x => x.Address).SetValidator(new NorweiganAdressValidator());
            });
        }
    }
```

Say we have a 2-step registration process to collect User information.
Both steps each have a `<EditForm Model="@user" ...>` and somehow we know which country the user resides in.

1. Validate a form with fields for  Username + Password + PasswordConfirmation

2. Validate another form with PhoneNumber + Adress fields (here we would like to select RuleSet based on country and validate on submit)


I think that @shirados90 suggestion was being able to define RuleSet like this
 `<FluentValidationValidator RuleSet="default, Swedish Adress"/>`

**Comment by GioviQ** [comment]
The partial validation use case is a wizard where each step has to be manually validated before the next step. So the rule set is based on all fields present in one wizard step. The proper wizard navigation logic has to be created.

**Comment by petgus** [comment]
Thanks for the reply @GioviQ .

Still think it would be very nice to be able to configure it like this. :)
`<FluentValidationValidator RuleSet="default, SomeRuleSet, AnotherRuleSet"/>`

Maybe I'll look into contributing with a PR for something like that further down the road.
