### ISSUE TITLE
Add credits / link to article to readme?

### ISSUE THREAD

**Issue by StefH** [Blazored/FluentValidation#6]
Maybe an idea to add credits + a link to the original article (https://chrissainty.com/using-fluentvalidation-for-forms-validation-in-razor-components/) in the readme.md file?

**Comment by chrissainty** [comment]
This repo has a different version of the code than in that post. Plus, I think crediting myself seems a bit over the top :)

**Comment by StefH** [comment]
Maybe copy some details from the post to the readme?

**Comment by chrissainty** [comment]
Better docs is now covered by https://github.com/Blazored/Home/issues/1. Closing this issue in favor of that one.
