### ISSUE TITLE
Using SetValidator with a validator inheriting from AbstractValidator<string> doesn't seem to come through

### ISSUE THREAD

**Issue by o-l-i-g** [Blazored/FluentValidation#62]
**Describe the bug**
SetValidator doesn't seem to set for vlidators inheriting from AbstractValidator\<string\>. 

I could be because of the primitive type nature
(see https://github.com/FluentValidation/FluentValidation/issues/184)

However I have code (I can't share that sorry!) where in the backend API where the validator behaviour is "as expected". 
So, a validator with a rule against a string type property is assigning a validator which inherits from AbstractValidator\<string\> - which is why I came here to see if it's possible to get that behaviour working in the blazor front end too! 

**To Reproduce**
Grab the sample code from repo.

Extend the SharedModels/Person.cs class the following:
(change the string type Person.EmailAddress validation to a dedicated validator, and try to use SetValidator to achieve it)

```

using FluentValidation;
using System.Threading.Tasks;

namespace SharedModels
{
    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? Age { get; set; }
        public string EmailAddress { get; set; }
        public Address Address { get; set; } = new Address();
    }

    public class PersonValidator : AbstractValidator<Person>
    {
        public PersonValidator()
        {
            RuleSet("Names", () =>
            {
                RuleFor(p => p.FirstName)
                .NotEmpty().WithMessage("You must enter your first name")
                .MaximumLength(50).WithMessage("First name cannot be longer than 50 characters");

                RuleFor(p => p.LastName)
                .NotEmpty().WithMessage("You must enter your last name")
                .MaximumLength(50).WithMessage("Last name cannot be longer than 50 characters");
            });

            RuleFor(p => p.Age)
                .NotNull().WithMessage("You must enter your age")
                .GreaterThanOrEqualTo(0).WithMessage("Age must be greater than 0")
                .LessThan(150).WithMessage("Age cannot be greater than 150");

            RuleFor(p => p.Address).SetValidator(new AddressValidator());

            RuleFor(p => p.EmailAddress).SetValidator(new EmailValidator()); // this doesn't work (i.e. does no validation - just passes any input given)

            //RuleFor(p => p.EmailAddress).EmailValidation(); // extension strategy also doesn't work

            //RuleFor(p => p.EmailAddress) // This works - because it's the original code :)
            //    .NotEmpty().WithMessage("You must enter a email address")
            //    .EmailAddress().WithMessage("You must provide a valid email address")
            //    .MustAsync(async (email, cancellationToken) => await IsUniqueAsync(email)).WithMessage("Email address must be unique").When(p => !string.IsNullOrEmpty(p.EmailAddress));

        }

        private async Task<bool> IsUniqueAsync(string email)
        {
            await Task.Delay(300);
            return email.ToLower() != "mail@my.com";
        }
    }

    public class EmailValidator : AbstractValidator<string>
    {
        public EmailValidator()
        {
            RuleFor(v => v).EmailAddress().WithMessage("must be good email");
        }
    }

    public static class Extensions
    {
        /// <summary>
        /// Inspired by https://github.com/FluentValidation/FluentValidation/issues/184#issuecomment-197952324
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="rule"></param>
        /// <returns></returns>
        public static IRuleBuilderOptions<T, string> EmailValidation<T>(this IRuleBuilder<T, string> rule)
        {
            return rule.EmailAddress().WithMessage("must be valid email");
        }
    }
}

```

Run the app, and click on "save".

Notice no validation was applied to Email field.

**Expected behavior**
Without having to configure anything, SetValidator(new EmailValidator()); to "work" in the sense that, in the front end when the save button is clicked the validation rules are executed, and the user is confronted with the error messages passed in the method WithMessage(" "). 

**Screenshots**
![image](https://user-images.githubusercontent.com/3698751/115117078-c1c7b900-9f94-11eb-98e2-b144b7aeb957.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**
The reason why I want this to work is because for some string properties it's not appropriate to create a complex type of its own, and the validation rules are to be shared across multiple validators - for example, passwords and phone number input - they should stay as string for me, and I have multiple use cases needing these validated, hence the need to share the validation logic against a string. I'm not too precious as to using the AbstractValidator<string> strategy v.s. extension method v.s. another way I haven't learned about -- but either way I do want to be able to use FluentValidation component for UI validation, with a shared collection of rules used against a string property! 

The example in this post is a little trivial since the built in validator has that, but I hope it illustrates the challenge.

**Comment by chrissainty** [comment]
Hi @o-l-i-g,

I've not come across/used this technique myself but I don't see why it shouldn't work if it's support by FluentValidation. I don't believe there is anything in this library which is actively stopping this working. Are you sure it's definitely an issue with this library and not something else?

**Comment by davibittencourtome** [comment]
Yes @chrissainty , I'm experiencing the same problem, any workaround?
