### ISSUE TITLE
[Question] Is there to have a rule like Contains/Any(class.AnotherProperty)?

### ISSUE THREAD

**Issue by thepra** [Blazored/FluentValidation#66]
I have a string in which I need to check if it does have a substring declared in another property of the same class, is there any way to achieve this?

**Comment by chrissainty** [comment]
This question is best directed to the [Fluent Validation repo](https://github.com/FluentValidation/FluentValidation). I'm just providing a wrapper to enable it with Blazor, not the underlying functionality.
