### ISSUE TITLE
FluentValidation 10.2.0 causes MissingMethodException in Blazored.FluentValidation

### ISSUE THREAD

**Issue by benghaner** [Blazored/FluentValidation#69]
**Describe the bug**
FluentValidation [10.2.0](https://github.com/FluentValidation/FluentValidation/releases/tag/10.2.0) causes the following MissingMethodException in Blazored.FluentValidation:

> System.MissingMethodException: Method not found: 'FluentValidation.AssemblyScanner FluentValidation.AssemblyScanner.FindValidatorsInAssembly(System.Reflection.Assembly)'.
         at Blazored.FluentValidation.EditContextFluentValidationExtensions.GetValidatorForModel(IServiceProvider serviceProvider, Object model, Boolean disableAssemblyScanning)...

**To Reproduce**
1. Install Blazored.FluentValidation 2.0.0 and FluentValidation 10.1.0.
2. Setup a Blazor form using fluent validation. The [samples](https://github.com/Blazored/FluentValidation/tree/main/samples) provided with this repo will work.
3. Launch the app and submit the form, no issue.
4. Upgrade to FluentValidation [10.2.0](https://github.com/FluentValidation/FluentValidation/releases/tag/10.2.0).
5. Launch the app again and submit the form. The exception occurs.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Tested using Blazor Server

**Additional context**
Probably caused by: Pull request [1742](https://github.com/FluentValidation/FluentValidation/pull/1742) Support Internal Types In AssemblyScanner

**Comment by xevimayo** [comment]
This is issue is very important to fix. When you install packages from Nuget in a clean project it just doesn't work at all and appears the error because nuget install FluentValidation 10.2.0. I spend one entire morning figuring out what was happens, till I found this issue.

**Comment by chrissainty** [comment]
Apologies for the delay on this one, folks. It's now going through to NuGet and should be available in the next 15-20 minutes.
