### ISSUE TITLE
Target NET 5?

### ISSUE THREAD

**Issue by RyanMarcotte** [Blazored/FluentValidation#71]
This library currently targets NET Standard 2.1 and includes the following dependencies:
- `Microsoft.AspNetCore.Components` (3.1.14)
- `Microsoft.AspNetCore.Components.Web` (3.1.14)
 
The 3.1.x versions of those two packages do not target NET 5, but the 5.0.x versions of those packages do.  FluentValidation itself targets NET 5.  Can this library target NET 5 with the appropriate 5.0.x Microsoft package dependencies?

**Comment by ABIOLI-COM** [comment]
I'm just starting to use this library, but I see that it refers versions 5.0.7 of those dependencies...

**Comment by ABIOLI-COM** [comment]
![image](https://user-images.githubusercontent.com/63686917/122402085-75d9c600-cf7d-11eb-9a39-853b9c0b1c54.png)

**Comment by chrissainty** [comment]
Closing this as we'll move straight to .NET 6
