### ISSUE TITLE
[Bug] ValidatorOptions.Global.LanguageManger Not being used

### ISSUE THREAD

**Issue by sianmace** [Blazored/FluentValidation#85]
I am using 

`ValidatorOptions.Global.LanguageManager = new LanguageManager(); `

but my validation messages are not picking up the updated messages...

Language Manager for info
```
public class LanguageManager : FluentValidation.Resources.LanguageManager
    {
        public LanguageManager()
        {
            AddTranslation("en-GB", "NotNullValidator", Messages.Required);
            AddTranslation("en-GB", "NotEmptyValidator", Messages.Required);
            AddTranslation("en-GB", "MinimumLengthValidator", Messages.MinLength);
            AddTranslation("en-GB", "MaximumLengthValidator", Messages.MaxLength);
            AddTranslation("en-GB", "EmailValidator", Messages.InvalidEmail);
```

I have used this approach in a .net core api successfully and the messages are picked up and overriden but not from blazor.

Any ideas?

**Comment by chrissainty** [comment]
Hi, I've not tried this before. I think this could be worth asking on the Fluent Validation repo as I don't think it's anything we handle. We don't deal with the messages we just trigger the validation process.

**Comment by sianmace** [comment]
Ok will do

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
