### ISSUE TITLE
Question: project contributor

### ISSUE THREAD

**Issue by StefH** [Blazored/FluentValidation#9]
Hello Chris,

I really like you `Blazored` projects. And I would like to contribute to a new project to render a **label** for model property like:
``` html
<LabelText For="@(() => Model.AccountNumber)" />
```
And this small component will also be using the *IStringLocalizer* to support localization.

Is it possible that I can be added as a contributor to create a new project in the `Blazored` organization?

Kind regards,
Stef

**Comment by chrissainty** [comment]
Hi Stef,

I'm glad you like the projects in Blazored. 

That would be awesome - Yes, I can create you a repository and add you as a contributor. In terms of naming Blazored.Label seems the obvious choice, unless you have any other suggestions?

**Comment by StefH** [comment]
`Blazored.Label` would be a good option indeed.

However, if we want to build more helpers, then maybe `Blazored.Forms` or `Blazored.Forms.Extensions` is also a good name (related to *Microsoft.AspNetCore.Components.Forms*)

Or `Blazored.Components.Forms` ?
Or `Blazored.Components` ? (maybe too generic...)

**Comment by chrissainty** [comment]
Almost all the projects in Blazored are component based so I wouldn't want to add Components to the namespace. I agree something like `Blazored.FormExtensions` may be a good option as it would provide a place for any form based bits to live.

`Blazored.Forms` may, again, be a bit to broad. For example Blazored.Typeahead is a form component and I would want to end up with some huge package which people had to install just to use a single component.

**Comment by StefH** [comment]
OK, just choose the best name.

**Comment by chrissainty** [comment]
Hi @StefH, apologies for the delay. I had some unexpected things come up. I'm just about to create the new repo, if you're still interested?

**Comment by StefH** [comment]
Yes. I am still interested.

**Comment by chrissainty** [comment]
You should have an invite waiting

**Comment by StefH** [comment]
Thanks.
