### ISSUE TITLE
Support for DisableDataAnnotationsValidation?

### ISSUE THREAD

**Issue by mikequ-taggysoft** [Blazored/FluentValidation#92]
The FluentValidation library for MVC/Razor pages has a configurable property `DisableDataAnnotationsValidation` that disables DataAnnotations attributes from triggering after the fluent rules.

Is it possible to use this property in this library?

I found that if annotations like `[Required]` are added to properties in entity class (not for validation purposes, but for things like EF Core), it sometimes triggers undesirable behaviors in UI when combined with FluentValidation. For example, if we define a  `NotEmpty()` rule that has a custom `WithMessage()`, the actual error message in the client UI would flop between the default message that comes with the `[Required]` annotation ("The field_name field is required") and the custom message we define in the validator class as the textbox goes in/out of focus (using MudBlazor).

**Comment by zachrybaker** [comment]
@chrissainty FWIW just because they use the System.ComponentModel.DataAnnotations attributes, doesn't mean that they are necessarily entities and not DTOs.
